### ISSUE TITLE
Add matrix Channel

### ISSUE THREAD

**Issue by frju365** [os-js/manual.os-js.org#17]
Hello : 

You ask me long time ago (1 month) to add suggestion of Matrix channel in the osjs manual... but I don't understand where I have to add this link.
![chat](https://user-images.githubusercontent.com/19982894/58807543-8b8b2580-8618-11e9-992f-2533a68521d0.png)

Little summary of advantages of having matrix channel (with no drawbacks) : 
- it's a chat channel to which you don't have to register (you can be anonymous)
- You don't have to link to an existing account (privacy) : github, facebook...
- Many features like Voice or video chat, service integration (GGle calendar, Etherpad, Gdrive...) 
- Gitter is integrated in it (as you can see on the screenshot) and you can make other bridge is you want (like to a forum to have announcement of the post -- for version announcement for example)

**Comment by andersevenrud** [comment]
I was thinking of this page: https://github.com/os-js/manual.os-js.org/tree/master/src/v3/resource/contrib

>You don't have to link to an existing account (privacy) : github, facebook...

Linking to an account actually has one *huge* benefit: keeping trolls out. Gitter might actually get an anonymous feature that can be assigned to specific rooms (I remember seeing this in their issue tracker).

> like to a forum to have announcement of the post

I actually have a bot that does this, but since you mentioned it I have to check the status of it, because I'm not sure it's running anymore :thinking:

**Comment by frju365** [comment]
ok. Yes. It's you decision. 

I saw indeed the page... but I didn't see anything which has to do with chat or community thing. I can create a category, but I don't know if it has its place here or even if it has place in a website. 

I know it keeps troll out... BUT, many users don't have a Github account, and that prevent I think many user from reporting bug or problem. And Github is a proprietary service owned by Microsoft. Many users left Github to other Git providers and so, remove Github account. 

It's your decision, but many feature of Matrix could be very nice to improve community.
